!pip install tensorflow2.0

In [1]:
# tensorflow 2.0
# magic command
try:
  %tensorflow_version 2.x
except Exception:
  pass

TensorFlow 2.x selected.


In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.1.0'

In [4]:
tf.executing_eagerly()

True

In [0]:
m1 = [[1.0, 2.0],
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
               [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                  [3.0, 4.0]])

In [6]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [0]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [8]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [9]:
print(t1)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [11]:
# numpy 호환
ndarray = np.ones([3,3])
tensor = tf.multiply(ndarray, 42)
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [12]:
print(tf.constant("hello"))

tf.Tensor(b'hello', shape=(), dtype=string)


In [10]:
# sess = tf.Session()
# print("OPEN SESSION")

OPEN SESSION


In [13]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print(a.numpy())
print(b)

1.5
tf.Tensor(2.5, shape=(), dtype=float32)


In [0]:
#placeholde 삭제됨

In [14]:
a = np.arange(10)
print(a)
ds_tensor = tf.data.Dataset.from_tensor_slices(a)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
ds_tensors = ds_tensor.map(tf.square).shuffle(20).batch(2)

In [18]:
print('ds_tensor')
for _ in range(3):
  for x in ds_tensor:
    print(x)

ds_tensor
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape

In [19]:
print('ds_tensor')
for _ in range(3):
  for x in ds_tensor.take(2):
    print(x)

ds_tensor
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)


In [0]:
def print_tf(x):
             print(type(x))
             print(x)

In [15]:
hello = tf.constant("hello")
print(hello)
print_tf(hello)

Tensor("Const_3:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const_3:0", shape=(), dtype=string)


In [18]:
hello_out = sess.run(hello)
print_tf(hello_out)

<class 'bytes'>
b'hello'


In [17]:
print_tf(sess.run(hello))

<class 'bytes'>
b'hello'


In [19]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const_4:0", shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const_5:0", shape=(), dtype=float32)


In [21]:
print_tf(sess.run(a))

print_tf(sess.run(b))

<class 'numpy.float32'>
1.5
<class 'numpy.float32'>
2.5


In [22]:
print_tf(tf.add(a,b))

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Add:0", shape=(), dtype=float32)


In [23]:
print_tf(sess.run(tf.add(a,b)))

<class 'numpy.float32'>
4.0


In [24]:
# variable
weight = tf.Variable(tf.random_normal([5,2], stddev=0.1))
print_tf(weight)

<class 'tensorflow.python.ops.variables.RefVariable'>
<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [0]:
tf.Variable?

In [26]:
print_tf(sess.run(weight))

FailedPreconditionError: ignored

In [0]:
sess.run(weight.initializer)

In [28]:
print_tf(sess.run(weight))

<class 'numpy.ndarray'>
[[ 0.03562292 -0.05627115]
 [-0.08493514  0.07898144]
 [-0.05150142 -0.21639791]
 [ 0.07002553 -0.04194453]
 [ 0.07661073 -0.0774181 ]]


In [0]:
# 변수한번에 초기화하기
init = tf.global_variables_initializer()
sess.run(init)

In [0]:
# tf.get_variable

In [30]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [31]:
oper = tf.matmul(x, weight)
print_tf(oper)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [32]:
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x:data})
print_tf(oper_out)

<class 'numpy.ndarray'>
[[-0.06513973  0.06309567]]


In [0]:
sess.close()